name: Udeps

on:
  push:
    branches:
      - dev
      - develop
      - main
  pull_request:
    branches:
      - dev
      - develop
      - main

concurrency: 
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  udeps:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Get current date
      run: echo "CURRENT_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

    - name: Cache CARGO_HOME
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
        # Add date to the cache to keep it up to date
        key: ubuntu-latest-stable-cargo-home-${{ env.CURRENT_DATE }}
        # Restore from outdated cache for speed
        restore-keys: |
          ubuntu-latest-stable-cargo-home-

    - uses: actions-rs/cargo@v1
      with:
        command: install
        args: cargo-udeps --locked

    # Udeps needs to run with the nightly toolchain
    - name: Install nightly toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        override: true

    - name: Install required packages
      run: |
        sudo apt-get update
        sudo apt-get install libudev-dev libusb-1.0-0-dev

    - name: Cache cargo target
      uses: actions/cache@v3
      with:
        path: target
        key: ubuntu-latest-nightly-cargo-build-target-${{ hashFiles('**/Cargo.toml') }}

    - name: Cache nodejs binding cargo target
      uses: actions/cache@v3
      with:
        path: bindings/nodejs/target
        key: ubuntu-latest-nightly-cargo-build-node-target-${{ hashFiles('**/Cargo.toml') }}

    - name: Cache python binding cargo target
      uses: actions/cache@v3
      with:
        path: bindings/python/target
        key: ubuntu-latest-nightly-cargo-build-python-target-${{ hashFiles('**/Cargo.toml') }}

    - name: Run udeps
      uses: actions-rs/cargo@v1
      with:
        command: udeps
        args: --all-targets

    - name: Run udeps for Node.js
      uses: actions-rs/cargo@v1
      with:
        command: udeps
        args: --manifest-path ./bindings/nodejs/Cargo.toml --all-targets

    - name: Run udeps for Python
      uses: actions-rs/cargo@v1
      with:
        command: udeps
        args: --manifest-path ./bindings/python/Cargo.toml --all-targets
